# Generated by Django 5.1.2 on 2024-10-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('Degree', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
