# Generated by Django 5.1.2 on 2024-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmaster', '0002_my_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
