# Generated by Django 5.1.2 on 2024-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmaster', '0004_my_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
