# Generated by Django 5.1.2 on 2024-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.IntegerField(default=0)),
            ],
        ),
    ]
