# Generated by Django 5.1.2 on 2024-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsection', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('list_desc', models.CharField(max_length=200)),
                ('list_price', models.IntegerField(default=0)),
            ],
        ),
    ]
